site_name: "Terraform Cloud Run for ${{ values.app_name }}"
site_description: "This is a Terraform module for deploying docker image using Cloud Run. ${{ values.description }}"

nav:
  - Introduction: index.md